urls.py
from django.conf.urls import url
from . import views


     
app_name = "Pg"

urlpatterns = [
		    
			 url(r"^base/$", views.base, name="base"),
			 url(r"^about/$", views.about, name="about"),
			 url(r"^logo/$", views.logo, name="logo"),
			 url(r"^logo1/$", views.logo1, name="logo1"),
			 url(r'^mainpg/$', views.mainpg, name='mainpg'),
			 url(r'^q/$', views.q, name='q'),
			 url(r'^backg1/$', views.backg1, name='backg1'),
			 url(r'^backg2/$', views.backg2, name='backg2'),
			 url(r'^home/$', views.home, name='home'),
			 url(r'^cont/$', views.cont, name='cont'),
			 url(r'^how_it_works/$', views.how_it_works, name='how_it_works'),
			 url(r'^help_and_support/$', views.help_and_support, name='help_and_support'),
			 url(r'^Cust_register/$', views.Cust_register, name='Cust_register'),
			 url(r"^Cust_login/$", views.Cust_login, name="Cust_login"),
			 url(r"^logout/$", views.logout, name="logout"),
			 url(r"^Ldetails/$", views.Ldetails, name="Ldetails"),
			 url(r'^Land_register/$', views.Land_register, name='Land_register'),
			 url(r"^Ldisplay/$", views.Ldisplay, name="Ldisplay"),
			 url(r"^Cdetails/$", views.Cdetails, name="Cdetails"),
			 url(r"^Maindisplay/$", views.Maindisplay, name="Maindisplay"),
			 url(r"^payment/$", views.payment, name="payment"),
			 url(r"^forgot/$", views.forgot, name="forgot"),
             url(r"^Hostelselect/$", views.Hostelselect, name="Hostelselect"),
             url(r"^own_message/$", views.own_message, name="own_message"),
             
			
			 
		   ]
		   

models.py
from django.db import models
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PG_selection(models.Model):
    name = models.CharField(max_length=120)
 
    def __str__(self):
        return self.name

class Help_and_Support(models.Model):
    customer_name = models.CharField(max_length=120)
    email = models.EmailField()
    phone_no =  models.CharField(max_length=10)
    PG_selection = models.ForeignKey(PG_selection, on_delete=models.CASCADE)
    comments_on_PG = models.TextField()
    comments_on_website = models.TextField()
    satisfied = models.BooleanField()
    date = models.DateField(auto_now_add=True)
 
    def __str__(self):
        return self.customer_name

class Cust_Signup(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
   
    class Meta:
        model = User
        fields = ('username', 'email','password1', 'password2', )

        def __str__(self):
          return self.username

class Landdetails(models.Model):
    retype_username = models.CharField(max_length=250)
    retype_email =  models.EmailField()
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    Hostel_name = models.CharField(max_length=100)
    Address = models.CharField(max_length=500)
    Female_or_Male = models.CharField(max_length=50)
    Mess =  models.CharField(max_length=50, default='')
    Pictures = models.CharField(max_length=1000)
    Rent = models.CharField(max_length=500)
    date = models.DateField(auto_now_add=True)
   
    def __str__(self):
          return self.Hostel_name

class Designation(models.Model):
    name =  models.CharField(max_length=250)
    def __str__(self):
        return self.name


class Custdetails(models.Model):
    retype_username = models.CharField(max_length=250)
    retype_email =  models.EmailField()
    Phone_no =  models.CharField(max_length=10)
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    Date_of_Birth = models.DateField(null=True, blank=True)
    Female_or_Male = models.CharField(max_length=50)
    Designation = models.ForeignKey(Designation, on_delete=models.CASCADE)
    Address = models.CharField(max_length=500)
    date = models.DateField(auto_now_add=True)
   
        
    def __str__(self):
        return self.retype_username + ' - ' + self.first_name 

forms.py
from django import forms
 
from .models import Help_and_Support
 
 
class Help_and_SupportForm(forms.ModelForm):
    class Meta:
        model = Help_and_Support
        exclude = []

views.py
from django.http import HttpResponse
from django.shortcuts import render
from .forms import Help_and_SupportForm
from .formscust1 import Cust_SignupForm
from django.contrib.auth.views import  LoginView as auth_login
from django.contrib.auth import authenticate as auth
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import  redirect
from django.contrib.auth.views import  LoginView as auth_login
from .models import Landdetails
from .formsld import LanddetailsForm
from .models import  Custdetails
from .formscd import CustdetailsForm


def base(request):
	return render(request,"base.html", {})
def about(request):
	return render(request,"about.html", {})
def logo(request):
	return render(request,"logo.html",{})
def logo1(request):
	return render(request,"logo1.html",{})
def q(request):
	return render(request,"q.html",{})
def mainpg(request):
	return render(request,"mainpg.html",{})
def backg1(request):
	return render(request,"backg1.html",{})
def home(request):
	return render(request,"home.html",{})
def backg2(request):
	return render(request,"backg2.html",{})
def cont(request):
	return render(request,"cont.html", {})
def how_it_works(request):
	return render(request,"how_it_works.html", {})
def help_and_support(request):

	if request.method == 'POST':
		form = Help_and_SupportForm(request.POST)
 
		if form.is_valid():
			form.save()
			return render(request, 'help_and_support.html')
	else:
		form = Help_and_SupportForm()
	return render(request, 'help_and_support.html', {'form': form})

def Cust_register(request):
	if request.method == 'POST':
		form = Cust_SignupForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = auth(username=username, password=raw_password)
			
			form = CustdetailsForm()
			return render(request, 'Cdetails.html', {'form': form})

	else:
		form = Cust_SignupForm()
	return render(request, 'signup.html', {'form': form})

def Land_register(request):
	if request.method == 'POST':
		form = Cust_SignupForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = auth(username=username, password=raw_password)
			
			form = LanddetailsForm()
			return render(request, 'Ldetails.html', {'form': form})
	else:
		form = Cust_SignupForm()
	return render(request, 'signupl.html', {'form': form})


def Cust_login(request):
	
	context = {}
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = auth(request, username=username, password=password)
		if user:
			all_landd = Landdetails.objects.all()
			return render(request,"Maindisplay.html", {"all_landd" : all_landd})
		else:
			context['error'] = "provide valid crendetials"
			return render(request, "log.html", context)
	else:
		return render(request, "log.html", context)

def logout(request):
	return render(request, "logout.html", {})

def Ldetails(request):
	if request.method == 'POST':
		form = LanddetailsForm(request.POST)
 
		if form.is_valid():
			form.save()
			return render(request, 'own_message.html', {'form': form})
	else:
		form = LanddetailsForm()
	return render(request, 'Ldetails.html', {'form': form})

def Ldisplay(request):
	all_landd = Landdetails.objects.all()
	return render(request,"Ldisplay.html", {"all_landd" : all_landd})

def Cdetails(request):
	if request.method == 'POST':
		form = CustdetailsForm(request.POST)
 
		if form.is_valid():
			form.save()
			return render(request, 'log.html',  {'form': form})
	else:
		form = CustdetailsForm()
	return render(request, 'Cdetails.html', {'form': form})

def Maindisplay(request):
	all_landd = Landdetails.objects.all()
	return render(request,"Maindisplay.html", {"all_landd" : all_landd})



def payment(request):
	return render(request,"payment.html", {})

def forgot(request):
	return render(request,"forgot.html", {})

def Hostelselect(request):
	return render(request,"Hostelselect.html", {})

def own_message(request):
	return render(request,"own_message.html", {})

templates/Hostelselect.html
{% extends "q.html" %}
 {% load static %}
{% block content %}
<!DOCTYPE html>
  <html>
  <head>
    <title>Contact Form</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/select.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Datepicker - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
   $( function() {
    $( "#datepicker1" ).datepicker();
  } );
  </script>
  </head>
<body background= "{% static 'imgs/greenwall.jpg' %}">
    <div class="form">
      <form name="ss" action="{% url 'Pg:payment' %}" method="post">
        {% csrf_token %}
        <h2>Fix Dates</h2>
        
    <div class="input-box">
          <i class="fa fa-calendar" aria-hidden="true"></i>
          <label for="Check_in"> Check_in</label>
          <input type="Check_in" name="" placeholder="MM-DD-YYYY" id="datepicker" required="">
          
        </div>
        <div class="input-box">
          <i class="fa fa-calendar" aria-hidden="true"></i>
          <label for="Check_out"> Check_out</label>
          <input type="Check_out" name="" placeholder="MM-DD-YYYY" id="datepicker1" required="">
          <p><br>
        </div>
        <div class="input-box">
         <center> <h3 style="color: grey;"><input type="submit" value="Payment">
        </div>

         </form>
</body>
</html>
{% endblock %}

templates/Ldetails.html
{% extends "q.html" %}
 {% load static %}
{% block content %}
<!DOCTYPE html>
  <html>
  <head>
    <title>Contact Form</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>
    <body background= "{% static 'imgs/greenwall.jpg' %}">
    <div class= "form">
    <form action="{% url 'Pg:Ldetails' %}" method="POST">
      
    {% csrf_token %}
     <h2>Fill Out Details</h2>
   <br>{{ form.as_p }}
   <center>
    <div class="input-box">
          <input type="submit" name="" value="Sign me Up">
        </div></a>
</div>
         </form>
</body>
</html>
{% endblock %}

templates/Ldisplay.html
{% extends "q.html" %}
 {% load static %}
{% block content %}

<center> <font face="ALGERIAN " size =6 color="black"> THE LIST OF HOSTELS </font></center>
<p><b> <center><font face="Cooper Black " size = 5 color="blue"> Note : This is only a view page, you have to a user in order to select these hostels</font> </p></center>
<ul>
	{% for landdetails in all_landd %} 
	<li><left>
		<table border=1 width=100%>
			<tr align="center">
				<th><center><font face="Cooper Black " size =5 color="black"> Hostel Picture</th>
				<th><center> <font face="Cooper Black " size =5 color="black">Hostel Name</th>
				<th><center><font face="Cooper Black " size =5 color="black"> Owner Name</th>
				<th><center><font face="Cooper Black " size =5 color="black"> Address</center></th>
				<th><center><font face="Cooper Black " size =5 color="black">Rent</th>
			    <th><center><font face="Cooper Black " size =5 color="black">Mess</th>
				<th><center><font face="Cooper Black " size =5 color="black">Gender</th>
				
			</tr>

			<tr align="center">
				<td><img src="{{landdetails.Pictures}}" width=200 height=200></td>
				<td><font face="Arial " size =4 color="black">{{landdetails.Hostel_name}}</td>
				<td><font face="Arial  " size =4 color="black">{{landdetails.first_name}} {{landdetails.last_name}}</td>
				<td><font face="Arial  " size =4 color="black"> {{landdetails.Address}}</td>
				<td><font face="Arial  " size =4 color="black">{{landdetails.Rent}}</td>
				<td><font face="Arial  " size =4 color="black">{{landdetails.Mess}}</td>
				<td><font face="Arial " size =4 color="black">{{landdetails.Female_or_Male}}</td>
							</tr>
	 -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  
	</li>
	{% endfor %}
	
</ul>
{% endblock %}

templates/backg2.html
{% load static %}
<html>
<title>LOGO</title>
<body background="{% static 'imgs/blue.jpg' %}">
	

</body>
</html>

templates/base.html
{% load static %}
<html>
<title>FindMePG</title>
<frameset  cols="9%,*" framespacing="0">
<frame name="logo" src="{% url 'Pg:logo' %}" frameborder="0" scrolling=no>
<frameset  cols="87%,*" framespacing="0">
<frame name="logo" src="{% url 'Pg:mainpg' %}" frameborder="0" scrolling=no>
<frameset  cols="100%,*" framespacing="0">
<frame name="logo" src="{% url 'Pg:logo' %}" frameborder="0" scrolling=no>


</frameset>
</html>

templates/cont.html
{% extends "q.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
	<html>
	<head>
		<title>Contact Form</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/cont.css' %}">
		<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	</head>
	<body background= "{% static 'imgs/greenwall.jpg' %}">
		<div class="form">
			<form>
				<center><h2>Contact Us</h2></center>
				<div class="input-box">
					<i class="fa fa-mobile" aria-hidden="true"></i>
					<label for="Mobile"> <font face="Cooper Black " size =4 color="black">Mobile:9527594758</font></label>
				</div>
				<div class="input-box">
					<i class="fa fa-envelope" aria-hidden="true"></i>
					<label for="mail"> <font face="Cooper Black" size =4 color="black">Email:FindMePg@gmail.com</font></label>
					
				</div>
				<div class="input-box">
					<i class="fa fa-globe" aria-hidden="true"></i>
					<label for="web"> <font face="Cooper Black " size =4 color="black"> Web:www.FindMePG.com </font> </label>
				</div>
				
		</div>
	</body>
	</html>	
{% endblock %}

templates/forgot.html
{% extends "q.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
	<html>
	<head>
		<title>Log In Form</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/cont.css' %}">
		<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	</head>
	<body background="{% static 'imgs/greenwall.jpg' %}">
		<div class="form">
			<form>
				<h2>Forgot Password?</h2>
				<p><b><font face="Cooper Black" size =3 color="black">Don't worry! Just write your email id down below and we'll send it your email.
				</font></p>
				
				<div class="input-box">
					
					<center><input type="email" name="" placeholder="Email" required="">
				</div>
				<center>
				<div class="input-box">
					<input type="submit" name="" value="Confirm" onclick="myFunction()">
				</div>

			

				<script>
				function myFunction() {
					alert("Your email has been sent!!")
				}
				</script></center>
				<a href="{% url 'Pg:Cust_login' %}"><h4>Back</h4></a>	
		</div>
					</div>	
					
		</div>
		
	</body>
	</html>	

{% endblock %}

templates/help_and_support.html
{% extends "q.html" %}
 {% load static %}
{% block content %}
<!DOCTYPE html>
  <html>
  <head>
    <title>Contact Form</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/help.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>
  <body background= "{% static 'imgs/greenwall.jpg' %}">
    <div class= "form">
    <form action="{% url 'Pg:home' %}" method="POST">
      
    {% csrf_token %}
     <h2><i class="fa fa-user" aria-hidden="true"></i> Help & Support</h2>
   <br>{{ form.as_p }}
   <div class="input-box">
          <input type="submit" name="" value="Submit">
        </div>

      

       

</div>
         </form>
     
         
     
  </body>
  </html>
{% endblock %}

templates/home.html
{% extends "q.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>FindMe_PG</title>
  <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>


<div class="container">
 <center> <h1 style="color: darkblue;"><b>A HOME AWAY FROM HOME!</b></h1>
    <h2 style="color: blue">Student looking for a stress-free stay?</h2><br><br>
    <p><font face="Cooper Black" size =6  color="black">Here we are! Book a PG room and get assured of all the key amenities.</font></p></center>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
        <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" style="height: 500px;">

      <div class="item active">
        <img src="{% static 'imgs/room.jpg' %}" style="width:100%; max-height: 500px;">
        <div class="carousel-caption">
          <h3 style="color:red;"><B>WE ARE HERE WITH LARGEST INVENTORY OF ACCOMODATION!</B></h3>
        </div>
      </div>

      <div class="item">
        <img src="{% static 'imgs/room1.jpg' %}" style="width:100%; max-height: 500px;">
        <div class="carousel-caption">
          <h3 style="color:red;"><B>GET A ROOM AS PER YOUR REQUIREMENT!</B></h3>
        </div>
      </div>
    
      <div class="item">
        <img src="{% static 'imgs/room2.jpg' %}" style="width:100%;max-height: 500px;">
        <div class="carousel-caption">
          <h3 style="color:red;"><B>WE GUARANTEE TO OFFER YOU THE BEST AVAILABLE RATES!</B></h3>
        </div>
      </div>
    <div class="item">
        <img src="{% static 'imgs/room3.jpg' %}" style="width:100%; max-height: 500px;">
        <div class="carousel-caption">
          <h3 style="color:red;" ><B>FULLY FURNISHED PG AVAILABLE ON RENT HERE!</B></h3>
        </div>
      </div>
        
 <div class="item">
        <img src="{% static 'imgs/room4.jpg' %}" style="width:100%; max-height: 500px">
        <div class="carousel-caption">
          <h3 style="color:red;"><b>FIND A PLACE THAT FITS ALL YOUR PREFERENCES.</b></h3>
        </div>
      </div>       
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
<center><p><b>   <h3 style="color:blue;"><b>TO VIEW THE HOSTELS CLICK HERE.<a href="{% url 'Pg:Ldisplay' %}"> HERE</a></b></h3></b>
  <br><br>
 <div class="col-md-12 col-sm-12">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-4 col-sm-4">
                  <h3><p align = "center">GET TO KNOW US</h3>
                  <ul>
                    <ul>
                    <li><a href=#><font face="arial " size =5 color="blue">Home</font></a></li>
                    <li><a href="{% url 'Pg:about' %}"><font face="arial" size =5 color="blue">About Us</font></a></li>
          
                    </ul>
                  </ul>
                </div>
                <div class="col-md-4 col-sm-4">
                  <h3>CONTACT WITH US</h3>
                  <ul>
                    <li><a href="{% url 'Pg:cont' %}"><font face="arial" size =5 color="blue">Contact Us</font></a></li>
                  
                    
                 <li><a href="{% url 'Pg:help_and_support' %}"><font face="arial " size =5 color="blue">Feedback</font></a></li>
                  </ul>
                </div>
                <div class="col-md-4 col-sm-4">
                  <h3>LET US HELP YOU</h3>
                  <ul>
                    
                     <li><a href="{% url 'Pg:how_it_works' %}"><font face="arial " size =5 color="blue">How It Works</font></a></li>
          
                  </ul>
                 
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
    </div>

    </center>            
              
  
   
</body>
</html>


{% endblock %}

templates/log.html
{% extends "q.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
	<html>
	<head>
		<title>Log In Form</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
		<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	</head>
	 <body background= "{% static 'imgs/greenwall.jpg' %}">
<div class ="form">
<form method = "POST" action="{% url 'Pg:Cust_login' %}">
	{% csrf_token %}
	<center><h2>Log In</h2></center>
	<table>
		<tr>
			<td><font face="Cooper Black" size =5 color="grey"><i class="fa fa-user" aria-hidden="true"></i> Username: </label></td>
			<td><input type = "text" name="username" id="username" required="True"></td></font>
		</tr>
		<tr>
			<td><br><font face="Cooper Black" size =5 color="grey"><i class="fa fa-unlock-alt" aria-hidden="true"></i> Password: </label></td><p>
			<td><br><input type = "text" name="password" id="password" required="True"></td></font>
		</tr>
		
		<p>{{error}}</p>
	</table>	
	
<p><p>
<div class="input-box">
					<input type="submit" name="" value="Login">
				</div>

			<center>	<a href="{% url 'Pg:forgot' %}">Forget Password !</a>
				

</form>


</body>

	</html>	
{% endblock %}

templates/logo.html
{% load static %}
<html>
<title>LOGO</title>
<body background="{% static 'imgs/blur1.jpg' %}">
</body>
</html>

templates/payment.html
{% extends "q.html" %}
{% block content %}
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <title>Credit/Debit card</title>

  <!-- Styles -->
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,300,100' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/pay.css' %}">
  <meta name="robots" content="noindex,follow" />
</head>

<body background= "{% static 'imgs/greenwall.jpg' %}">
    <form class="credit-card">
      <div class="form-header">
        <h4 class="title">Card detail</h4>
      </div>

    
      <div class="form-body">
        <!-- Card Number -->
         <form action="{% url 'Pg:payment' %}" method="POST">
        {% csrf_token %}
         
        <input type="text" class="card-number" placeholder="Card Number" required="">

        <!-- Date Field -->
        <div class="date-field">
          <div class="month">
            <select name="Month">
              <option value="january">January</option>
              <option value="february">February</option>
              <option value="march">March</option>
              <option value="april">April</option>
              <option value="may">May</option>
              <option value="june">June</option>
              <option value="july">July</option>
              <option value="august">August</option>
              <option value="september">September</option>
              <option value="october">October</option>
              <option value="november">November</option>
              <option value="december">December</option>
            </select>
          </div>
          <div class="year">
            <select name="Year">
              
              <option value="2018">2018</option>
              <option value="2019">2019</option>
              <option value="2020">2020</option>
              <option value="2021">2021</option>
              <option value="2022">2022</option>
              <option value="2023">2023</option>
              <option value="2024">2024</option>
            </select>
          </div>
        </div>

        <!-- Card Verification Field -->
        <div class="card-verification">
          <div class="cvv-input">
            <input type="text" placeholder="CVV" required="">
          </div>
          <div class="cvv-details">
            <p>3 or 4 digits usually found <br> on the signature strip</p>
          </div>
        

           
        
        </div>
        <button type="submit" class="proceed-btn">Confirm</button>
      </div>
    </form>
</body>

</html>



{% endblock %}

templates/signup.html
{% extends "q.html" %}
 {% load static %}
{% block content %}
<!DOCTYPE html>
  <html>
  <head>
    <title>Contact Form</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/sign_up.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>
    <body background= "{% static 'imgs/greenwall.jpg' %}">
    <center><font face="algerian " size =6 color="black"><b></font>
    <div class= "form">
    <form action="{% url 'Pg:Cust_register' %}" method="POST">
      <h2>Sign Up</h2>
    {% csrf_token %}
       {% for field in form %}
       <i class="fa fa-user" aria-hidden="true"></i>

       <h4> {{ field.label_tag }}</h4>
        {{ field }}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
   
    <div class="input-box">
           <input type="submit" name="" value="Move on to Next">
        </div>
        <div class="text-center p-t-115">
            <span class="txt1">
              I already have an account.
            </span>
            <a href="{% url 'Pg:Cust_login' %}">Log In</a>
          </div>      
    </div>
  </body>

            
  </html>  
   
{% endblock %}

           

templates/thanks.html
{% extends 'q.html' %}
 {% block content %}
<h1>Thanks for your response.</h1>
<p><a href="{% url 'Pg:help_and_support' %}">Response again?</a></p>
{% endblock %}